### ISSUE TITLE
Pytest or Unittest?

### ISSUE THREAD

**Issue by dvc-77** [aglili/arkesel#1]
Hi! Is there a particular reason why you used both testing frameworks @aglili

**Comment by aglili** [comment]
No Particular Reason. I just came up with those tests

**Comment by dvc-77** [comment]
Pardon me though, but wouldn't it be right to stay consistent with one test framework. Pytest can't run unittest mock.

**Comment by aglili** [comment]
Yeah, I was in a hurry cos i wanted to move on to other things. starting sunday i'll be kind of free so i will do that. If you can i'll appreciate it

**Comment by dvc-77** [comment]
Sure, let me quickly make a PR then

**Comment by aglili** [comment]
thanks
